export interface FactItem {
  fact: string;
  topic: string;
  image?: string;
}

export const FACTS: FactItem[] = [
  { fact: "Honey never spoils.", topic: "Honey" },
  { fact: "Bananas are berries, but strawberries are not.", topic: "Banana" },
  { fact: "A group of flamingos is called a 'flamboyance'.", topic: "Flamingo" },
  { fact: "The unicorn is the national animal of Scotland.", topic: "Unicorn" },
  { fact: "Octopuses have three hearts.", topic: "Octopus" },
  { fact: "The Eiffel Tower can be 15 cm taller during hot days.", topic: "Eiffel Tower" },
  { fact: "Wombat poop is cube-shaped.", topic: "Wombat" },
  { fact: "Sloths can hold their breath longer than dolphins.", topic: "Sloth" },
  { fact: "Sharks existed before trees.", topic: "Shark" },
  { fact: "Otters hold hands while they sleep so they don’t drift apart.", topic: "Otter" },
  { fact: "There’s a species of jellyfish that can live forever.", topic: "Jellyfish" },
  { fact: "Elephants can recognize themselves in a mirror.", topic: "Elephant" },
  { fact: "Water can boil and freeze at the same time.", topic: "Water" },
  { fact: "An octopus can taste with its arms.", topic: "Octopus" },
  { fact: "Your brain generates enough electricity to power a light bulb.", topic: "Brain" },
  { fact: "Koalas have fingerprints almost identical to humans.", topic: "Koala" },
  { fact: "A shrimp’s heart is in its head.", topic: "Shrimp" },
  { fact: "Saturn could float in water because it’s less dense than water.", topic: "Saturn" },
  { fact: "Butterflies remember being caterpillars.", topic: "Butterfly" },
  { fact: "A bolt of lightning is five times hotter than the surface of the sun.", topic: "Lightning" },
  { fact: "Cheetahs can’t roar; they meow like house cats.", topic: "Cheetah" },
  { fact: "The heart of a blue whale is the size of a small car.", topic: "Blue whale" },
  { fact: "Dolphins have names for each other.", topic: "Dolphin" },
  { fact: "Sharks don’t have bones.", topic: "Shark" },
  { fact: "There are more fake flamingos in the world than real ones.", topic: "Flamingo" },
  { fact: "Hummingbirds are the only birds that can fly backward.", topic: "Hummingbird" },
  { fact: "Sea otters have the thickest fur of any animal.", topic: "Sea otter" },
  { fact: "Giraffes only sleep for about 30 minutes a day.", topic: "Giraffe" },
  { fact: "Carrots were originally purple, not orange.", topic: "Carrot" },
  { fact: "The longest hiccup spree lasted 68 years.", topic: "Hiccup" },
  { fact: "Turtles can breathe through their butts.", topic: "Turtle" },
  { fact: "Your taste buds have a lifespan of about 10 days.", topic: "Taste bud" },
  { fact: "The fingerprints of a koala are so similar to humans that they can confuse crime scene investigators.", topic: "Koala fingerprint" },
  { fact: "Penguins propose to each other with pebbles.", topic: "Penguin" },
  { fact: "Cows can walk up stairs, but not down them.", topic: "Cow" },
  { fact: "A snail can sleep for three years at a time.", topic: "Snail" },
  { fact: "Crows can hold grudges for years.", topic: "Crow" },
  { fact: "Slugs have four noses.", topic: "Slug" },
  { fact: "There’s enough DNA in your body to stretch from the sun to Pluto and back.", topic: "DNA" },
  { fact: "Camels have three eyelids to protect against sandstorms.", topic: "Camel" },
  { fact: "A single strand of spider silk is five times stronger than steel of the same thickness.", topic: "Spider silk" },
  { fact: "An ostrich’s eye is bigger than its brain.", topic: "Ostrich" },
  { fact: "The fingerprints of twins are not identical.", topic: "Twin fingerprint" },
  { fact: "Dragonflies can see in almost every direction at once.", topic: "Dragonfly" },
  { fact: "Bees can recognize human faces.", topic: "Bee" },
  { fact: "Humans share about 60% of their DNA with bananas.", topic: "Banana DNA" },
  { fact: "Sharks can live for over 400 years.", topic: "Shark" },
  { fact: "The tongue is the only muscle in your body attached at just one end.", topic: "Tongue" },
  { fact: "A crocodile cannot stick its tongue out.", topic: "Crocodile" },
  { fact: "Jellyfish don’t have brains.", topic: "Jellyfish" },
  { fact: "Gorillas can catch human colds.", topic: "Gorilla" },
  { fact: "There are more bacteria in your mouth than people on Earth.", topic: "Bacteria" },
  { fact: "Bananas glow blue under black light.", topic: "Banana" },
  { fact: "A cloud can weigh more than a million pounds.", topic: "Cloud" },
  { fact: "Rats and mice laugh when tickled.", topic: "Rat" },
  { fact: "Octopus blood is blue because it uses copper instead of iron.", topic: "Octopus" },
  { fact: "The world’s oldest known living tree is over 4,800 years old.", topic: "Old tree" },
  { fact: "Ants never sleep.", topic: "Ant" },
  { fact: "There’s a basketball court on the top floor of the U.S. Supreme Court building nicknamed ‘the highest court in the land’.", topic: "Supreme Court" },
  { fact: "Sharks existed 100 million years before dinosaurs.", topic: "Shark" },
  { fact: "The tongue print is as unique as a fingerprint.", topic: "Tongue print" },
  { fact: "A group of crows is called a murder.", topic: "Crow" },
  { fact: "Kangaroos can’t walk backward.", topic: "Kangaroo" },
  { fact: "Peanuts aren’t nuts, they’re legumes.", topic: "Peanut" },
  { fact: "Oysters can change their gender multiple times.", topic: "Oyster" },
  { fact: "An eagle’s eyesight is about 8 times stronger than a human’s.", topic: "Eagle" },
  { fact: "Humans can’t breathe and swallow at the same time.", topic: "Human" },
  { fact: "The moon has moonquakes.", topic: "Moonquake" },
  { fact: "Rabbits can’t vomit.", topic: "Rabbit" },
  { fact: "Apples float in water because they are 25% air.", topic: "Apple" },
  { fact: "The dot over an “i” is called a tittle.", topic: "Tittle" },
  { fact: "A giraffe has the same number of neck bones as a human (7).", topic: "Giraffe" },
  { fact: "The longest time between two twins being born is 87 days.", topic: "Twin" },
  { fact: "Spiders can’t fly, but some use silk threads to glide through the air (‘ballooning’).", topic: "Spider" },
  { fact: "Your body has enough iron to make a small nail.", topic: "Iron" },
  { fact: "Sea cucumbers can eject their internal organs as a defense mechanism.", topic: "Sea cucumber" },
  { fact: "The shortest war in history was between Britain and Zanzibar in 1896 — it lasted 38 minutes.", topic: "Shortest war" },
  { fact: "Sharks are immune to almost all known diseases.", topic: "Shark" },
  { fact: "Some cats are allergic to humans.", topic: "Cat" },
  { fact: "The human stomach gets replaced with a new lining every few days.", topic: "Stomach" },
  { fact: "Rats can swim for days without drowning.", topic: "Rat" },
  { fact: "There’s a species of ant that only exists in Manhattan.", topic: "Ant" },
  { fact: "The inventor of the Pringles can is buried in one.", topic: "Pringles" },
  { fact: "Dolphins sleep with one eye open.", topic: "Dolphin" },
  { fact: "The average person walks about 100,000 miles in a lifetime.", topic: "Walking" },
  { fact: "Sea otters have a favorite rock they use to crack open shells.", topic: "Sea otter" },
  { fact: "Wolves communicate using 200 different sounds.", topic: "Wolf" },
  { fact: "The longest word in English is 189,819 letters long (a protein name).", topic: "Longest word" }
];
